language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install scripttest
  - pip install nose
  - pip install unittest2 || true
  - pip install .
# command to run tests
script: nosetests
