language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-nose
  - sudo apt-get install python-scripttest
install:
  - sudo python setup.py develop
# command to run tests
script: nosetests
